# Generated by Django 5.1.4 on 2025-01-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization_settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameter_variant",
            name="value",
        ),
    ]
