# Generated by Django 5.1.4 on 2025-01-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization_settings", "0002_remove_parameter_variant_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Limit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                (
                    "model",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization_settings.model",
                    ),
                ),
            ],
        ),
    ]
