# Generated by Django 5.1.4 on 2025-02-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization_settings", "0003_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="limits",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
