# Generated by Django 5.1.4 on 2025-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization_settings", "0004_model_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="parameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
